Homework 2
algakbk/MyFirstApplication pull request #1
Opened 2020-11-27 17:24 UTC by algakbk

Homework 3
- couldn't finish the "Cast" color which is the Linear Gradient
- colors, size and some style's are still hardcoded 
@an-yurii please review and give comments where need to improve

2020-11-28 09:28 UTC, an-yurii requested changes
Чтобы сверстать рейтинг можно воспользоваться компонентом или просто картинок накидать
```
        <RatingBar
            android:id="@+id/ratingBar"
            style="?android:attr/ratingBarStyleSmall"
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:layout_marginStart="@dimen/layout_gap"
            android:layout_marginTop="8dp"
            android:isIndicator="true"
            android:numStars="5"
            android:rating="4"
            android:theme="@style/RatingBarStyle"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tvGenres" />
```
С остальным контентом - все просто. Верстаешь сверху-вниз)

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/values-night/themes.xml
> +        <item name="colorOnPrimary">@color/colorBlack</item>
По ссылке понятно, что это - цвет `@color/black`. Верни как было.

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/values/colors.xml
> +    <color name="colorTransparent">#FFFFFFFF</color>
Здесь и далее. Без префикса color. При использовании это и так понятно.
```suggestion
    <color name="transparent">#FFFFFFFF</color>
```

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/values/colors.xml
> +    <color name="movie_name">#ECECEC</color>
Годная статья про именование цветов в палитре https://habr.com/ru/company/redmadrobot/blog/523916/

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_4x">16dp</dimen>
В размеры стоит выносить только стандартные параметры, например, отступы слева и справа по краям экрана. Остальные размеры лучше константами указывать в макете. Так как верстка, обычно, уникальная для каждого экрана.

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +<!-- drawable/mask.xml -->
Этот файл случайно изменил?

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        android:layout_height="match_parent"
```suggestion
        android:layout_height="wrap_content"
```

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:id="@+id/back_text"
Иконку добавить через атрибут `app:drawableLeftCompat="@drawable/ic_baseline_arrow_back"`

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:background="@drawable/path"
Возьми стандартную иконку в студии. Из фигмы не подходит для Андроид
![image](https://user-images.githubusercontent.com/31529762/100498446-deee1d80-3194-11eb-9255-2235136e9afa.png)

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +<!--        <ImageView-->
Добавь вью с ресурсом - градиент и привяжи ее к границам изображения. Примерно так:
```
        <View
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:background="@drawable/gradient"
            app:layout_constraintBottom_toBottomOf="@+id/imgTitlePoster"
            app:layout_constraintEnd_toEndOf="@+id/imgTitlePoster"
            app:layout_constraintStart_toStartOf="@+id/imgTitlePoster"
            app:layout_constraintTop_toTopOf="@+id/imgTitlePoster" />
```

Градиент
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle" >
    <gradient
        android:angle="90"
        android:centerColor="@android:color/transparent"
        android:startColor="@color/background" />
    <corners android:radius="0dp" />
</shape>
```

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginStart="@dimen/space_2x"
Просто используй константу, например `4dp`.

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginLeft="@dimen/space_4x"
```suggestion
            android:layout_marginHorizontal="@dimen/space_4x"
```

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintTop_toBottomOf="@+id/topMovieImage"
Нужно верхнюю и нижнюю границы привязать к нижнему краю изображения. Пример:
```
app:layout_constraintBottom_toBottomOf="@+id/imgTitlePoster"
app:layout_constraintTop_toBottomOf="@+id/imgTitlePoster"
```

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:id="@+id/pg_rectangle"
Этот элемент не нужен. Просто оставь @+id/pg_name

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_height="16dp"
Указывай размеры по контенту `wrap_content` Размеры самой вьюхи определяются размерами шрифта и паддингами (если они нужны)

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintBottom_toBottomOf="@+id/topMovieImage"
Нужно привязать к верхнему краю @+id/movie_name

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        <androidx.constraintlayout.widget.Barrier
На этом макете барьеры не нужны.

2020-11-28 09:28 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +    <!--    <ImageView-->
Смотри пример как сверстать список актеров с подписями
```
        <ImageView
            android:id="@+id/imgDowney"
            style="@style/ImageViewActorStyle"
            android:layout_marginStart="@dimen/layout_gap"
            android:contentDescription="@string/image_of_actor_or_actress"
            app:layout_constraintEnd_toStartOf="@+id/imgEvans"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintHorizontal_chainStyle="spread_inside"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tvCast"
            app:srcCompat="@drawable/img_downey" />

        <TextView
            android:id="@+id/tvDowney"
            style="@style/TextImageStyle"
            android:layout_width="@dimen/actor_icon_size"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/text_under_image_view_gap"
            android:gravity="start"
            android:maxLines="2"
            android:text="@string/robert_downey_jr"
            app:layout_constraintEnd_toEndOf="@+id/imgDowney"
            app:layout_constraintStart_toStartOf="@+id/imgDowney"
            app:layout_constraintTop_toBottomOf="@+id/imgDowney" />

        <ImageView
            android:id="@+id/imgEvans"
            style="@style/ImageViewActorStyle"
            android:contentDescription="@string/image_of_actor_or_actress"
            app:layout_constraintEnd_toStartOf="@+id/imgRuffalo"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toEndOf="@+id/imgDowney"
            app:layout_constraintTop_toBottomOf="@+id/tvCast"
            app:srcCompat="@drawable/img_evans" />

        <TextView
            android:id="@+id/tvEvans"
            style="@style/TextImageStyle"
            android:layout_width="@dimen/actor_icon_size"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/text_under_image_view_gap"
            android:gravity="start"
            android:maxLines="2"
            android:text="@string/chris_evans"
            app:layout_constraintEnd_toEndOf="@+id/imgEvans"
            app:layout_constraintStart_toStartOf="@+id/imgEvans"
            app:layout_constraintTop_toBottomOf="@+id/imgEvans" />
```

2020-11-28 09:30 UTC, an-yurii commented
> couldn't finish the "Cast" color which is the Linear Gradient
Не используй градиент. Похоже, в макете - ошибка.

2020-11-28 09:45 UTC, algakbk commented
> Чтобы сверстать рейтинг можно воспользоваться компонентом или просто картинок накидать
> 
> ```
>         <RatingBar
>             android:id="@+id/ratingBar"
>             style="?android:attr/ratingBarStyleSmall"
>             android:layout_width="wrap_content"
>             android:layout_height="0dp"
>             android:layout_marginStart="@dimen/layout_gap"
>             android:layout_marginTop="8dp"
>             android:isIndicator="true"
>             android:numStars="5"
>             android:rating="4"
>             android:theme="@style/RatingBarStyle"
>             app:layout_constraintStart_toStartOf="parent"

2020-11-28 09:51 UTC, algakbk commented on app/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +<!-- drawable/mask.xml -->
да случайно

2020-11-28 10:16 UTC, algakbk commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:id="@+id/back_text"
а как ему цвет изменять?

2020-11-30 14:34 UTC, an-yurii approved these changes
Поправишь замечания и можно вливать)

2020-11-30 14:34 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintTop_toBottomOf="@+id/tagline" />
Выровнять по ревьюверам
```
app:layout_constraintTop_toTopOf="@+id/review" 
app:layout_constraintBottom_toBottomOf="@+id/review"
```

2020-11-30 14:34 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="8dp"
Если привязаться к ревьюерам, этот отступ не нужен.

2020-11-30 14:34 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_height="20dp"
Размер TextView определется параметрами шрифта. Здесь и для остальных вьюх нужно установить высоту по контенту
```
android:layout_height="wrap_content"
```

2020-12-01 16:33 UTC, merged